/*
 * generated by Xtext
 */
package gama.export;

import java.nio.file.Path;
import java.util.prefs.Preferences;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleContext;
import org.osgi.framework.BundleActivator;

import gama.api.utils.prefs.JREPreferenceStore;
import gama.api.runtime.SystemInfo;
import gama.api.utils.prefs.GamaPreferenceStore;
import gama.dev.FLAGS;

public class ExportActivator implements BundleActivator {

	protected static String appRootPathStr = null;

	protected static String eclipsePathStr = null;

    @Override
    public void start(BundleContext context) throws Exception {
      
        eclipsePathStr = System.getProperty("eclipse.home.location");
        eclipsePathStr = eclipsePathStr.replaceAll("file:", "");

        if(SystemInfo.isWindows())
        {
            int index = 0;
            while (eclipsePathStr.charAt(index) == '\\' || eclipsePathStr.charAt(index) == '/')
                index++;
            
            if (index > 0)
                eclipsePathStr = eclipsePathStr.substring(index);
        }

        appRootPathStr = eclipsePathStr;

        if (SystemInfo.isMac())
            appRootPathStr = Path.of(appRootPathStr)
                .getParent().getParent().toString();


    }

    @Override
    public void stop(BundleContext context) throws Exception {

    }
}
