/*
 * generated by Xtext
 */
package gama.export;

import com.google.inject.Injector;
import gama.export.ExportActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GamlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ExportActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ExportActivator activator = ExportActivator.getInstance();
		return activator != null ? activator.getInjector(ExportActivator.GAML_COMPILER_GAML) : null;
	}

}
