/**
 * generated by Xtext
 */
package gaml.compiler.gaml.impl;

import gaml.compiler.gaml.ActionFakeDefinition;
import gaml.compiler.gaml.GamlPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Action Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ActionFakeDefinitionImpl extends ActionDefinitionImpl implements ActionFakeDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActionFakeDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.ACTION_FAKE_DEFINITION;
  }

} //ActionFakeDefinitionImpl
