/**
 * generated by Xtext
 */
package gaml.compiler.gaml.impl;

import gaml.compiler.gaml.GamlPackage;
import gaml.compiler.gaml.imageDisplayStatement;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>image Display Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class imageDisplayStatementImpl extends StatementImpl implements imageDisplayStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected imageDisplayStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.IMAGE_DISPLAY_STATEMENT;
  }

} //imageDisplayStatementImpl
