/**
 * generated by Xtext
 */
package gaml.compiler.gaml.impl;

import gaml.compiler.gaml.GamlPackage;
import gaml.compiler.gaml.ReservedLiteral;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Reserved Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ReservedLiteralImpl extends TerminalExpressionImpl implements ReservedLiteral
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReservedLiteralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.RESERVED_LITERAL;
  }

} //ReservedLiteralImpl
