/**
 * generated by Xtext
 */
package gaml.compiler.gaml.impl;

import gaml.compiler.gaml.GamlPackage;
import gaml.compiler.gaml.S_EventLayer;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SEvent Layer</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_EventLayerImpl extends StatementImpl implements S_EventLayer
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_EventLayerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamlPackage.Literals.SEVENT_LAYER;
  }

} //S_EventLayerImpl
