source.. = src/,\
           gaml/
output.. = bin/
jre.compilation.profile = JavaSE-21
bin.includes = .,\
               plugin.xml,\
               META-INF/,\
               models/,\
               /src/gama/extension/image/icons/,\
               libs/jai-imageio-core 1.4.0/jai-imageio-core-1.4.0.jar

