/*******************************************************************************************************
 *
 * FuzzTestGenerator.java, in gama.processor, is part of the source code of the GAMA modeling and simulation platform.
 *
 * (c) 2007-2026 UMI 209 UMMISCO IRD/SU & Partners (IRIT, MIAT, ESPACE-DEV, CTU)
 *
 * Visit https://github.com/gama-platform/gama for license information and contacts.
 *
 ********************************************************************************************************/
package gama.processor.tests;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;

import javax.lang.model.element.Element;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.type.WildcardType;

import gama.annotations.no_fuzz_test;
import gama.annotations.no_test;
import gama.annotations.operator;
import gama.annotations.type;
import gama.processor.Constants;
import gama.processor.ProcessorContext;

/**
 * Generates the fuzz tests of the GAML operators and types declared in a plugin.
 *
 * <p>
 * Every operator (methods annotated with {@link operator}) is called with "edge" values for the types of its operands
 * (0, -1, the bounds of int, infinities and NaN for numbers; empty and non-ASCII strings; empty or nil-containing
 * containers; degenerate geometries; nil...), one operand at a time, the others keeping an ordinary value. Every type
 * (classes annotated with {@link type}) is used to cast a set of values of all kinds. The tests check that an invalid
 * input is either accepted or rejected with a GAML error, but never with an internal Java exception (reported by GAMA
 * as "Java error: ...").
 * </p>
 *
 * <p>
 * One test experiment is written per Java class declaring operators, alongside the tests generated by
 * {@link TestProcessor}, with one test per operator (and a separate one for its calls with nil operands). Nothing is
 * generated for the operators that are internal, iterators (their last operand is an expression, not a value),
 * annotated with {@link no_test} or {@link no_fuzz_test}, or that have an operand of a type for which no value is
 * known (see {@link #VALUES}).
 * </p>
 *
 * <p>
 * As there is no timeout in the test runner, an operator that never returns or exhausts the memory for one of these
 * values must be annotated with {@link no_fuzz_test}, with the reason, until it is fixed.
 * </p>
 */
public class FuzzTestGenerator {

	/** The line separator of the generated files. */
	private static final String ln = Constants.ln;

	/** The indentation of the generated files. */
	private static final String tab = Constants.tab;

	/**
	 * Whether to generate the calls with nil operands (in tests of their own, named "... with nil").
	 *
	 * OPEN QUESTION: most operators answer a nil operand with the generic "Java error: nil value detected", which
	 * these tests count as a failure like any other internal exception. Whether this message is an acceptable way
	 * of rejecting nil, or a lack of robustness to fix operator by operator, has not been decided yet. Until then the
	 * nil calls are kept apart from the others, so that their failures can be told (and filtered) at a glance. Set
	 * this constant to false to stop generating them.
	 */
	static final boolean WITH_NIL = true;

	/**
	 * The values of a type of operand.
	 *
	 * @param ordinary
	 *            a valid, unremarkable value
	 * @param edges
	 *            the values likely to reveal a lack of robustness
	 * @param nil
	 *            the name of the attribute of the experiment holding a nil of this type, or null if the type has none
	 */
	private record Values(String ordinary, List<String> edges, String nil) {}

	/** A string with characters outside of ASCII and of the basic multilingual plane. */
	private static final String ODD_STRING = "\"é ✓ 😀\"";

	/** The values for floats. */
	private static final Values FLOATS =
			new Values("1.5", List.of("0.0", "-1.0", "#infinity", "-#infinity", "#nan", "#max_float"), null);

	/** The values for ints. */
	private static final Values INTS = new Values("2", List.of("0", "-1", "#max_int", "#min_int"), null);

	/** The values for booleans. */
	private static final Values BOOLS = new Values("true", List.of("false"), null);

	/** The values for points. */
	private static final Values POINTS = new Values("{1, 2}",
			List.of("{0, 0}", "{#nan, #nan}", "{#infinity, -#infinity}", "{-1, -1, -1}"), "nil_point");

	/** The values for colors. */
	private static final Values COLORS = new Values("#red", List.of("rgb(0, 0, 0, 0)"), "nil_color");

	/** The values for dates. */
	private static final Values DATES = new Values("date(\"2026-01-01T00:00:00\")",
			List.of("date([])", "date(\"9999-12-31T23:59:59\")"), "nil_date");

	/** The values for fonts. */
	private static final Values FONTS = new Values("font(\"Arial\", 12)", List.of("font(\"\", 0)"), null);

	/** The values of the operands, by simple name of their (erased) Java type. Containers are handled apart. */
	private static final Map<String, Values> VALUES = new HashMap<>();

	/** An ordinary list for each known type of elements, by simple name of the Java type of the elements. */
	private static final Map<String, String> LISTS = new HashMap<>();

	static {
		VALUES.put("Double", FLOATS);
		VALUES.put("double", FLOATS);
		VALUES.put("Integer", INTS);
		VALUES.put("int", INTS);
		VALUES.put("Boolean", BOOLS);
		VALUES.put("boolean", BOOLS);
		VALUES.put("String", new Values("\"abc\"", List.of("\"\"", ODD_STRING, "\" \\n\\t \""), "nil_string"));
		VALUES.put("IShape", new Values("square(10) at_location {5, 5}",
				List.of("square(0)", "polygon([])", "line([{0, 0}, {0, 0}])"), "nil_geometry"));
		VALUES.put("IPoint", POINTS);
		VALUES.put("GamaPoint", POINTS);
		VALUES.put("IDate", DATES);
		VALUES.put("GamaDate", DATES);
		VALUES.put("IGraph", new Values("as_edge_graph([line([{0, 0}, {10, 0}]), line([{10, 0}, {10, 10}])])",
				List.of("graph([])"), "nil_graph"));
		VALUES.put("IMatrix", new Values("matrix([[1, 2], [3, 4]])", List.of("matrix([])", "matrix([[#nan]])"),
				"nil_matrix"));
		VALUES.put("IMap", new Values("[\"a\"::1]", List.of("map([])"), "nil_map"));
		VALUES.put("IPair", new Values("1::2", List.of("nil::nil"), "nil_pair"));
		VALUES.put("IColor", COLORS);
		VALUES.put("GamaColor", COLORS);
		VALUES.put("IAgent", new Values("world", List.of(), "nil_agent"));
		VALUES.put("Object", new Values("1", List.of("\"a\"", "[]", "{0, 0}"), "nil_value"));
		VALUES.put("IFont", FONTS);
		VALUES.put("GamaFont", FONTS);
		VALUES.put("IField", new Values("field(3, 3)", List.of("field(0, 0)"), null));
		VALUES.put("GamaImage", new Values("image(2, 2)", List.of("image(0, 0)"), null));
		VALUES.put("IDataFrame", new Values("dataframe_with([\"a\", \"b\"], [[1, 2], [3, 4]])",
				List.of("dataframe_with([], [])"), null));
		VALUES.put("Predicate", new Values("new_predicate(\"p\")", List.of("new_predicate(\"\")"), null));
		VALUES.put("MentalState", new Values("new_mental_state(\"belief\", new_predicate(\"p\"))", List.of(), null));
		VALUES.put("Emotion", new Values("new_emotion(\"joy\")", List.of("new_emotion(\"\", -1.0)"), null));

		LISTS.put("IShape", "[square(1) at_location {1, 1}, circle(1) at_location {5, 5}]");
		LISTS.put("IPoint", "[{0, 0}, {1, 1}, {2, 0}]");
		LISTS.put("GamaPoint", "[{0, 0}, {1, 1}, {2, 0}]");
		LISTS.put("Double", "[1.0, 2.0, 3.0]");
		LISTS.put("Integer", "[1, 2, 3]");
		LISTS.put("String", "[\"a\", \"b\"]");
		LISTS.put("IAgent", "[world]");
		LISTS.put("IList", "[[1, 2], [3, 4]]");
		LISTS.put("IColor", "[#red, #blue]");
	}

	/**
	 * The GAML type of contents and an ordinary list for the operators that declare the type of contents they expect
	 * (expected_content_type, checked at compile time), by id of the type (see IType).
	 */
	private static final Map<Integer, String[]> TYPED_LISTS = new HashMap<>();

	static {
		TYPED_LISTS.put(1, new String[] { "int", "[1, 2, 3]" });
		TYPED_LISTS.put(2, new String[] { "float", "[1.0, 2.0, 3.0]" });
		TYPED_LISTS.put(3, new String[] { "bool", "[true, false]" });
		TYPED_LISTS.put(4, new String[] { "string", "[\"a\", \"b\"]" });
		TYPED_LISTS.put(5, new String[] { "list", "[[1, 2], [3, 4]]" });
		TYPED_LISTS.put(6, new String[] { "rgb", "[#red, #blue]" });
		TYPED_LISTS.put(7, new String[] { "point", "[{0, 0}, {1, 1}, {2, 0}]" });
		TYPED_LISTS.put(9, new String[] { "pair", "[1::2, 3::4]" });
		TYPED_LISTS.put(13, new String[] { "geometry", "[square(1) at_location {1, 1}, circle(1) at_location {5, 5}]" });
	}

	/** The values cast to every type. */
	private static final List<String> CAST_VALUES = List.of("0", "-1", "#max_int", "1.5", "#nan", "#infinity",
			"-#infinity", "true", "\"\"", "\"abc\"", "\"12\"", "\"2026-01-01\"", "\"#FF0000\"", "{1, 2}", "{#nan, 0}",
			"#red", "date(\"2026-01-01T00:00:00\")", "[]", "[1, 2, 3]", "[[1, 2], [3]]", "[\"a\"::1]", "map([])",
			"matrix([[1, 2], [3, 4]])", "matrix([])", "square(10) at_location {5, 5}", "polygon([])", "1::2",
			"graph([])", "world", "nil_value");

	/** The attributes of the generated experiments: typed nil values, to pass nil to an operand of a given type. */
	private static final String[] NIL_ATTRIBUTES = { "geometry nil_geometry <- nil;", "point nil_point <- nil;",
			"date nil_date <- nil;", "graph nil_graph <- nil;", "matrix nil_matrix <- nil;", "map nil_map <- nil;",
			"pair nil_pair <- nil;", "rgb nil_color <- nil;", "agent nil_agent <- nil;", "string nil_string <- nil;",
			"list nil_list <- nil;", "container nil_container <- nil;", "unknown nil_value <- nil;" };

	/** The name of the group of tests of the casts. */
	private static final String CASTS = "Types";

	/** The calls collected so far: Java class -> name of the test -> calls. */
	private final Map<String, Map<String, Set<String>>> calls = new TreeMap<>();

	/**
	 * Collects the operators and types of the current round of annotation processing.
	 *
	 * @param context
	 *            the context of the processor
	 */
	public void collect(final ProcessorContext context) {
		for (final Element e : context.getElementsAnnotatedWith(operator.class)) {
			try {
				collectOperator(context, e);
			} catch (final Exception exception) {
				context.emitWarning("Fuzz tests could not be generated: " + exception.getMessage(), e);
			}
		}
		for (final Element e : context.getElementsAnnotatedWith(type.class)) { collectType(e); }
	}

	/**
	 * Whether there is something to write.
	 *
	 * @return true if calls have been collected
	 */
	public boolean hasElements() {
		return !calls.isEmpty();
	}

	/**
	 * Writes one test experiment per group of calls and forgets them.
	 *
	 * @param context
	 *            the context of the processor
	 */
	public void write(final ProcessorContext context) {
		for (final Map.Entry<String, Map<String, Set<String>>> group : calls.entrySet()) {
			try (Writer writer = context.createTestWriter(group.getKey() + " Fuzz Tests.experiment")) {
				if (writer != null) { writeExperiment(writer, group.getKey(), group.getValue()); }
			} catch (final IOException e) {
				context.emitWarning("An exception occured in the generation of fuzz tests: ", e);
			}
		}
		calls.clear();
	}

	/**
	 * Whether no fuzz test must be generated for an element.
	 */
	private boolean isExcluded(final Element e) {
		return e.getAnnotation(no_fuzz_test.class) != null || e.getAnnotation(no_test.class) != null;
	}

	/**
	 * Collects the casts to a type.
	 */
	private void collectType(final Element e) {
		final type t = e.getAnnotation(type.class);
		if (t == null || t.internal() || isExcluded(e) || !isIdentifier(t.name())) return;
		for (final String value : CAST_VALUES) {
			if ("nil_value".equals(value) && !WITH_NIL) { continue; }
			add(CASTS, "Cast to " + t.name() + ("nil_value".equals(value) ? " with nil" : ""),
					t.name() + "(" + value + ")");
		}
	}

	/**
	 * Collects the calls to an operator.
	 */
	private void collectOperator(final ProcessorContext context, final Element e) {
		final operator op = e.getAnnotation(operator.class);
		if (op == null || op.internal() || op.iterator() || isExcluded(e) || !(e instanceof ExecutableElement)) return;
		final ExecutableElement method = (ExecutableElement) e;
		// The operands: the instance on which the method is called, if any, then the parameters but the scope
		final List<TypeMirror> operands = new ArrayList<>();
		if (!method.getModifiers().contains(Modifier.STATIC)) { operands.add(method.getEnclosingElement().asType()); }
		for (final VariableElement parameter : method.getParameters()) {
			if (!"IScope".equals(simpleName(context, parameter.asType()))) { operands.add(parameter.asType()); }
		}
		if (operands.isEmpty()) return;
		final List<Values> values = new ArrayList<>();
		for (final TypeMirror operand : operands) {
			final Values v = valuesOf(context, operand, op.expected_content_type());
			if (v == null) return;
			values.add(v);
		}
		final String group = method.getEnclosingElement().getSimpleName().toString();
		for (final String name : op.value()) {
			if (!isIdentifier(name)) { continue; }
			add(group, "Operator " + name, call(name, values, -1, null));
			for (int i = 0; i < values.size(); i++) {
				for (final String edge : values.get(i).edges()) {
					add(group, "Operator " + name, call(name, values, i, edge));
				}
				if (WITH_NIL && values.get(i).nil() != null) {
					add(group, "Operator " + name + " with nil", call(name, values, i, values.get(i).nil()));
				}
			}
		}
	}

	/**
	 * Builds the call to an operator with the ordinary value of its operands, but for the one at index (if any).
	 */
	private String call(final String name, final List<Values> values, final int index, final String replacement) {
		final StringBuilder sb = new StringBuilder(name).append('(');
		for (int i = 0; i < values.size(); i++) {
			if (i > 0) { sb.append(", "); }
			sb.append(i == index ? replacement : values.get(i).ordinary());
		}
		return sb.append(')').toString();
	}

	/**
	 * Registers a call.
	 */
	private void add(final String group, final String test, final String call) {
		calls.computeIfAbsent(group, k -> new TreeMap<>()).computeIfAbsent(test, k -> new LinkedHashSet<>()).add(call);
	}

	/**
	 * Whether a name can be used in a functional call, like name(operand, ...).
	 */
	private boolean isIdentifier(final String name) {
		return name != null && name.matches("[A-Za-z_][A-Za-z_0-9]*");
	}

	/**
	 * The simple name of the erasure of a type (e.g. IList for gama.api.types.list.IList&lt;IShape&gt;).
	 */
	private String simpleName(final ProcessorContext context, final TypeMirror t) {
		if (t.getKind().isPrimitive()) return t.toString();
		final String name = context.getTypeUtils().erasure(t).toString();
		return name.substring(name.lastIndexOf('.') + 1);
	}

	/**
	 * The values to use for an operand, or null if its type is not handled.
	 */
	private Values valuesOf(final ProcessorContext context, final TypeMirror t, final int[] expectedContents) {
		final String name = simpleName(context, t);
		final boolean isList = "IList".equals(name) || "List".equals(name);
		if (!isList && !"IContainer".equals(name)) return VALUES.get(name);
		if (expectedContents != null && expectedContents.length > 0) return typedValues(expectedContents);
		// The type of the elements is the last type argument of the container
		String elements = null;
		if (t.getKind() == TypeKind.DECLARED) {
			final List<? extends TypeMirror> arguments = ((DeclaredType) t).getTypeArguments();
			if (!arguments.isEmpty()) {
				TypeMirror last = arguments.get(arguments.size() - 1);
				if (last.getKind() == TypeKind.WILDCARD) { last = ((WildcardType) last).getExtendsBound(); }
				if (last != null) { elements = simpleName(context, last); }
			}
		}
		final List<String> edges = new ArrayList<>(List.of("[]", "[nil]"));
		// Mixed elements only make sense when the type of the elements is not constrained
		if (elements == null || "Object".equals(elements)) { edges.add("[[1, 2], \"a\", {1, 2}]"); }
		if (!isList) { edges.add("map([])"); }
		return new Values(LISTS.getOrDefault(elements, "[1, 2, 3]"), edges, isList ? "nil_list" : "nil_container");
	}

	/**
	 * The values of a container operand of an operator that declares the types of contents it expects. As these
	 * types are checked at compile time, only lists of the first known one are used: empty or nil-containing lists
	 * of unknown contents would not be valid GAML.
	 */
	private Values typedValues(final int[] expectedContents) {
		for (final int id : expectedContents) {
			final String[] typed = TYPED_LISTS.get(id);
			if (typed == null) { continue; }
			final List<String> edges = new ArrayList<>(List.of("list<" + typed[0] + ">([])"));
			if (id == 1) { edges.add("[0]"); }
			if (id == 2) {
				edges.add("[0.0]");
				edges.add("[#nan, 1.0]");
				edges.add("[#infinity, -#infinity]");
			}
			return new Values(typed[1], edges, null);
		}
		return null;
	}

	/**
	 * Writes the experiment testing a group of calls.
	 */
	private void writeExperiment(final Writer writer, final String group, final Map<String, Set<String>> tests)
			throws IOException {
		final StringBuilder sb = new StringBuilder();
		sb.append("/**").append(ln);
		sb.append("* GENERATED at compile time by gama.processor (FuzzTestGenerator), do not edit.").append(ln);
		sb.append("* ").append(CASTS.equals(group) ? "Casts a set of values of all kinds to the types declared in this plugin"
				: "Calls the operators declared in " + group + " with edge values, one operand at a time,").append(ln);
		sb.append("* and checks that an invalid input is rejected with a GAML error rather than with an internal")
				.append(ln);
		sb.append("* Java exception. Operators and types are left out with the @no_fuzz_test annotation.").append(ln);
		sb.append("*/").append(ln).append(ln);
		sb.append("model ").append(group).append("FuzzTests").append(ln).append(ln);
		sb.append("experiment ").append(toGamlString("Fuzz tests of " + group)).append(" type: test {").append(ln);
		sb.append(ln).append(tab).append("// typed nil values, to pass nil to the operands of a given type");
		for (final String attribute : NIL_ATTRIBUTES) { sb.append(ln).append(tab).append(attribute); }
		sb.append(ln).append(ln).append(tab)
				.append("// true if there was no error, or a GAML one; 'call' is only there to show up in the reports");
		sb.append(ln).append(tab).append("bool handled(string problem, string call) {");
		sb.append(ln).append(tab).append(tab)
				.append("return problem = nil ? true : !(problem contains \"Java error\");");
		sb.append(ln).append(tab).append("}").append(ln);
		for (final Map.Entry<String, Set<String>> test : tests.entrySet()) {
			sb.append(ln).append(tab).append("test ").append(toGamlString(test.getKey())).append(" {");
			sb.append(ln).append(tab).append(tab).append("string problem;");
			for (final String call : test.getValue()) {
				sb.append(ln).append(tab).append(tab).append("problem <- nil;");
				sb.append(ln).append(tab).append(tab).append("try { unknown result <- ").append(call)
						.append("; } catch { problem <- #current_error; }");
				sb.append(ln).append(tab).append(tab).append("assert handled(problem, ").append(toGamlString(call))
						.append(");");
			}
			sb.append(ln).append(tab).append("}").append(ln);
		}
		sb.append("}").append(ln);
		writer.append(sb);
	}

	/**
	 * Returns a GAML string literal.
	 */
	private String toGamlString(final String s) {
		return '"' + s.replace("\\", "\\\\").replace("\"", "\\\"") + '"';
	}

}
