javacDefaultEncoding..=UTF-8
source.. = src/,\
           src-gen/ 
src.excludes = gaml/
bin.includes = model/generated/,\
               model/,\
               META-INF/,\
               .,\
               plugin.xml
output.. = bin/