source.. = src/
output.. = bin/
jre.compilation.profile = JavaSE-25
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               libs/gt-render-33.4.jar,\
               libs/gt-process-33.4.jar,\
               libs/gt-process-feature-33.4.jar,\
               libs/gt-process-geometry-33.4.jar,\
               libs/gt-process-raster-33.4.jar
javacDefaultEncoding.. = UTF-8
