source.. = src/
output.. = bin/
jre.compilation.profile = JavaSE-25
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               libs/gt-render-33.4.jar,\
               libs/gt-process-33.4.jar,\
               libs/gt-process-feature-33.4.jar,\
               libs/gt-process-geometry-33.4.jar,\
               libs/gt-process-raster-33.4.jar,\
               libs/jt-classbreaks-1.1.31.jar,\
               libs/jt-contour-1.6.0.jar,\
               libs/jt-jiffle-language-1.1.31.jar,\
               libs/jt-jiffle-op-1.1.31.jar,\
               libs/jt-rangelookup-1.6.0.jar,\
               libs/jt-vectorize-1.6.0.jar,\
               libs/gt-graph-33.4.jar
javacDefaultEncoding.. = UTF-8
