source.. = src/,\
           gaml/
output.. = bin/
jre.compilation.profile = JavaSE-25
bin.includes = META-INF/,\
               plugin.xml,\
               .,\
               libs/joml-1.10.5.jar
javacDefaultEncoding.. = UTF-8
