source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               lib/jzy3d-core-2.2.1.jar,\
               lib/jzy3d-io-xls-2.2.1.jar,\
               lib/jzy3d-jdt-core-2.2.1.jar,\
               lib/jzy3d-native-jogl-core-2.2.1.jar,\
               lib/jzy3d-native-jogl-newt-2.2.1.jar,\
               lib/jzy3d-native-jogl-swt-2.2.1.jar
