source.. = src/,\
           gaml/
output.. = bin/
jre.compilation.profile = JavaSE-25
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               models/,\
               tests/,\
               about.ini,\
               gama.feature.serialize.png,\
               gama.feature.serialize@2x.png,\
               libs/fory-core-1.7.4.jar
javacDefaultEncoding.. = UTF-8
