source.. = src/,\
           gaml/
output.. = bin/
jre.compilation.profile = JavaSE-25
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               libs/,\
               models/,\
               about.ini,\
               gama.feature.serialize.png,\
               gama.feature.serialize@2x.png,\
               libs/afs-4.2.0.jar,\
               libs/base-4.2.0.jar,\
               libs/persistence-4.2.0.jar,\
               libs/persistence-binary-4.2.0.jar,\
               libs/serializer-4.2.0.jar
javacDefaultEncoding.. = UTF-8
