source.. = src/,\
           gaml/
output.. = bin/
jre.compilation.profile = JavaSE-25
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               models/,\
               libs/,\
               libs/SPARQL/caffeine-3.2.3.jar,\
               libs/SPARQL/com.google.gson-2.9.1.jar
javacDefaultEncoding.. = UTF-8
