/**
 * generated by Xtext
 */
package gaml.compiler.gaml;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Facets And Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gaml.compiler.gaml.FacetsAndBlock#getFacets <em>Facets</em>}</li>
 *   <li>{@link gaml.compiler.gaml.FacetsAndBlock#getBlock <em>Block</em>}</li>
 *   <li>{@link gaml.compiler.gaml.FacetsAndBlock#getKey <em>Key</em>}</li>
 *   <li>{@link gaml.compiler.gaml.FacetsAndBlock#getFirstFacet <em>First Facet</em>}</li>
 * </ul>
 *
 * @see gaml.compiler.gaml.GamlPackage#getFacetsAndBlock()
 * @model
 * @generated
 */
public interface FacetsAndBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Facets</b></em>' containment reference list.
   * The list contents are of type {@link gaml.compiler.gaml.Facet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Facets</em>' containment reference list.
   * @see gaml.compiler.gaml.GamlPackage#getFacetsAndBlock_Facets()
   * @model containment="true"
   * @generated
   */
  EList<Facet> getFacets();

  /**
   * Returns the value of the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' containment reference.
   * @see #setBlock(Block)
   * @see gaml.compiler.gaml.GamlPackage#getFacetsAndBlock_Block()
   * @model containment="true"
   * @generated
   */
  Block getBlock();

  /**
   * Sets the value of the '{@link gaml.compiler.gaml.FacetsAndBlock#getBlock <em>Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block</em>' containment reference.
   * @see #getBlock()
   * @generated
   */
  void setBlock(Block value);

  /**
   * Returns the value of the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' attribute.
   * @see #setKey(String)
   * @see gaml.compiler.gaml.GamlPackage#getFacetsAndBlock_Key()
   * @model
   * @generated
   */
  String getKey();

  /**
   * Sets the value of the '{@link gaml.compiler.gaml.FacetsAndBlock#getKey <em>Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' attribute.
   * @see #getKey()
   * @generated
   */
  void setKey(String value);

  /**
   * Returns the value of the '<em><b>First Facet</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Facet</em>' attribute.
   * @see #setFirstFacet(String)
   * @see gaml.compiler.gaml.GamlPackage#getFacetsAndBlock_FirstFacet()
   * @model
   * @generated
   */
  String getFirstFacet();

  /**
   * Sets the value of the '{@link gaml.compiler.gaml.FacetsAndBlock#getFirstFacet <em>First Facet</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Facet</em>' attribute.
   * @see #getFirstFacet()
   * @generated
   */
  void setFirstFacet(String value);

} // FacetsAndBlock
