/**
 * generated by Xtext
 */
package gaml.compiler.gaml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gaml.compiler.gaml.GamlPackage#getGamlDefinition()
 * @model
 * @generated
 */
public interface GamlDefinition extends EObject
{
} // GamlDefinition
