/**
 * generated by Xtext
 */
package gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>image Display Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gaml.compiler.gaml.GamlPackage#getimageDisplayStatement()
 * @model
 * @generated
 */
public interface imageDisplayStatement extends Statement
{
} // imageDisplayStatement
