/**
 * generated by Xtext
 */
package gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SCallable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gaml.compiler.gaml.GamlPackage#getS_Callable()
 * @model
 * @generated
 */
public interface S_Callable extends S_Definition, ActionArguments
{
} // S_Callable
