/**
 * generated by Xtext
 */
package gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SData</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gaml.compiler.gaml.GamlPackage#getS_Data()
 * @model
 * @generated
 */
public interface S_Data extends Statement, GamlDefinition
{
} // S_Data
