/**
 * generated by Xtext
 */
package gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SDo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gaml.compiler.gaml.S_Do#getTarget <em>Target</em>}</li>
 *   <li>{@link gaml.compiler.gaml.S_Do#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see gaml.compiler.gaml.GamlPackage#getS_Do()
 * @model
 * @generated
 */
public interface S_Do extends Statement, FacetsAndBlock
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference.
   * @see #setTarget(Expression)
   * @see gaml.compiler.gaml.GamlPackage#getS_Do_Target()
   * @model containment="true"
   * @generated
   */
  Expression getTarget();

  /**
   * Sets the value of the '{@link gaml.compiler.gaml.S_Do#getTarget <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' containment reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Expression value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference.
   * @see #setArgs(ExpressionList)
   * @see gaml.compiler.gaml.GamlPackage#getS_Do_Args()
   * @model containment="true"
   * @generated
   */
  ExpressionList getArgs();

  /**
   * Sets the value of the '{@link gaml.compiler.gaml.S_Do#getArgs <em>Args</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Args</em>' containment reference.
   * @see #getArgs()
   * @generated
   */
  void setArgs(ExpressionList value);

} // S_Do
