/**
 * generated by Xtext
 */
package gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SImage Layer</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gaml.compiler.gaml.GamlPackage#getS_ImageLayer()
 * @model
 * @generated
 */
public interface S_ImageLayer extends Statement
{
} // S_ImageLayer
