/**
 * generated by Xtext
 */
package gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SSpecies</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gaml.compiler.gaml.GamlPackage#getS_Species()
 * @model
 * @generated
 */
public interface S_Species extends Statement, S_Declaration, TypeDefinition
{
} // S_Species
