/**
 * generated by Xtext
 */
package gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gaml.compiler.gaml.GamlPackage#getTypeDefinition()
 * @model
 * @generated
 */
public interface TypeDefinition extends GamlDefinition, ActionDefinition
{
} // TypeDefinition
