/**
 * generated by Xtext
 */
package gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unit Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gaml.compiler.gaml.GamlPackage#getUnitFakeDefinition()
 * @model
 * @generated
 */
public interface UnitFakeDefinition extends GamlDefinition
{
} // UnitFakeDefinition
