/**
 * generated by Xtext
 */
package gaml.compiler.gaml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see gaml.compiler.gaml.GamlPackage#getVarFakeDefinition()
 * @model
 * @generated
 */
public interface VarFakeDefinition extends VarDefinition
{
} // VarFakeDefinition
