source.. = src/,\
           gaml/
output.. = bin/
jre.compilation.profile = JavaSE-25
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               models/,\
               tests/,\
               gama.feature.extension.png,\
               gama.feature.extension@2x.png
javacDefaultEncoding.. = UTF-8
