#!/bin/bash

# Set the list delimiter to newline
IFS=$'\n'
# exit on error
set -e

NEED_TO_SIGN_FILENAME="needToSign.txt"

# sign the input jar file and its sub jar files (recursive function)
function signInJar(){
    local jarfile="$1" # input file to sign
    local file
    local nested_jarfile

    # TODO : Prevent gathering META-INF folder
    filelist=($(jar tf "$jarfile" | grep '\.so\|\.dylib\|\.jnilib' | sed -e '/META-INF/d' ))

    if [ ${#filelist[@]} -gt 0 ]; then
        echo "$jarfile"

        for file in "${filelist[@]}"
        do
            jar xf "$jarfile" "$file"
            codesign --timestamp --options=runtime --force -s "$MACOS_DEV_ID" -v "$file"

            jar uf "$jarfile" "$file"
        done

    fi

    nestedJarfiles=($(grep "^\[$jarfile" $needToSignFile | sed 's/^\[[^]]*\] //'))

    if [ ${#nestedJarfiles[@]} -gt 0 ]; then
        for nested_jarfile in "${nestedJarfiles[@]}"
        do
            jar xf "$jarfile" "$nested_jarfile"

            echo "Signing in nested $nested_jarfile"
            mkdir "_sub" && cd "_sub"
            signInJar "../$nested_jarfile"
            cd ".." && rm -fr "_sub"
            echo "---"
            
            jar uf "$jarfile" "$nested_jarfile"
        done
    else
        echo "No nested file to sign in $jarfile"
    fi
}

# Get absolute path of the file needToSign.txt which is generated by the script travis/what2sign.sh
needToSignFile=$(find $(pwd) -name $NEED_TO_SIGN_FILENAME)
echo $needToSignFile

echo "=== Now ==="

# Extract .jar files from the list
jarfiles=($(grep "^./" $needToSignFile))

# Sign .jar files

# Looping through jar files and signing them, as well as sub jar files
for jarfile in "${jarfiles[@]}"
do
    # Check if the line $j is an existing file
    if [  -f "$jarfile" ]; then
        # actual signing
        echo "Signing in $jarfile"
        signInJar "$jarfile" # recursive

        # Clean-up the workspace
        find $(pwd) -not -wholename "*Gama.app*" -not -name "$needToSignFile" -not -name "*${NEED_TO_SIGN_FILENAME}" -delete
        echo "xxx"
    fi
done

# Sign single lib files
find ./ \( -name "*dylib" -o -name "*.so" -o -name "*.jnilib" \) -exec codesign --timestamp --options=runtime --force -s "$MACOS_DEV_ID" -v {} \;

# Clean-up apple mess
find ./Gama.app -name "jar*.tmp" -delete