source.. = src/
output.. = bin/
jre.compilation.profile = JavaSE-25
bin.includes = META-INF/,\
               .,\
               build.properties,\
               .project,\
               .classpath,\
               plugin.xml,\
               src/gama/processor/resources/
javacDefaultEncoding.. = UTF-8
