/*
 * generated by Xtext
 */
package gaml.compiler.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;

import gaml.compiler.GamlRuntimeModule;
import gaml.compiler.GamlStandaloneSetup;

import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GamlIdeSetup extends GamlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GamlRuntimeModule(), new GamlIdeModule()));
	}
	
}
