name: "[./.github/workflows/travis-packaging-linux-test.yaml]"

on:
  workflow_call:
    inputs:
      RELEASE_VERSION: 
        required: true
        default: 2024.03.0 
        type: string

jobs:
  debian-test-installer:
    runs-on: ubuntu-latest
    steps:
      # Get Linux deb archive
      - uses: actions/download-artifact@v2
        with:
          name: gama-linux-deb

      - name: Update apt databse
        run: |
          sudo apt update

      - name: Install, Run & Remove (w JDK)
        shell: bash
        run: |
          sudo apt install ./gama-platform-jdk_${{ inputs.RELEASE_VERSION }}-1_amd64.deb
          gama-headless -help

      - name: Install, Run & Remove (w/o JDK)
        shell: bash
        run: |
          sudo apt install -y ./gama-platform_${{ inputs.RELEASE_VERSION }}-1_amd64.deb
          # Switch to OpenJDK 17
          sudo update-java-alternatives -s $(update-java-alternatives -l | grep "\-openjdk" | cut -d " " -f 1)
          java -version
          gama-headless -help
          sudo apt remove -y gama-platform
