# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: "Pull Request validation"

on:
  # Triggers the workflow on pull request events
  pull_request:
  workflow_dispatch: # For manual trigger

jobs:

  compiling-gama:
    name: Compiling GAMA
    uses: ./.github/workflows/travis-build.yaml
    with:
      get_testing_compiled_archives: false
      get_all_archives_for_release: false
      RUN_SPOTBUGS: true

  spotbugs-result: 
    name: Display Spotbugs results
    runs-on: ubuntu-latest
    needs: compiling-gama
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: result-spotbugs

      - uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'