# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: "Continuous project validation"

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ 2024-06 ]
    paths-ignore:
      - '.github/**'
      - 'travis/**'

  workflow_dispatch: # For manual trigger

jobs:

  ci-handler:
    if: ${{ contains(github.event.head_commit.message, 'ci release') }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger release
        run: |
          echo "'ci release' Commit message detected!"
          echo "Triggering workflow '/.github/workflows/travis-gama-release.yaml'..."
          releaseVersion=$(date +"%Y").$(date +"%m").0
          #
          # Manually trigger the target workflow
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/gama-platform/gama/actions/workflows/trigger-gama-release.yaml/dispatches \
            -d "{\"ref\":\"${{ github.ref_name }}\",\"inputs\":{\"IS_STABLE_RELEASE\":false,\"tag\":\"$releaseVersion\"}}"

  compiling-gama:
    if: ${{ !contains(github.event.head_commit.message, 'ci release') }}
    name: Compiling GAMA
    uses: ./.github/workflows/travis-build.yaml
    with:
      get_testing_compiled_archives: true
      get_all_archives_for_release: false

  testing-gama:
    name: Testing built GAMA
    needs: compiling-gama
    uses: ./.github/workflows/travis-build-test.yaml
