/**
 *
 */
package gama.annotations;

import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/***
 * The test annotation is intended to provide a simpler syntax than @example for producing tests. It allows to write
 * unit tests for any GAML artefact. These tests are then automatically generated by the annotation processor and tested
 * during the compilation of GAMA, to ensure that the code is correct (and that no regressions affect it). Tests are
 * grouped together in test experiments (one experiment per GAMA plugin) that are automatically retrieved by GAMA (so
 * that they are also available in the UI or headless version of the platform). Depending on where they are located,
 * they are automatically named after the operator, constant, statement they annotate. For instance, for the '+'
 * operator, this annotation will produce:
 *
 * @test("10+10=20") -> test "+" { assert 10+10=20;}
 *
 * It is possible to give them a more explicit name:
 *
 * @test(value="10+10 = 20" name="int addition") -> test "int addition" { assert 10+10=20; }
 *
 * Several @test() annotations can be attached to an operator or constant. In that case, the corresponding assertions
 * are grouped together in a single GAML test statement. Example:
 *
 * @test("10+10=20") @test("0+0 = 0")
 *
 * will produce the following GAML test statement:
 *
 * test "+" { assert 10+10=20; assert 0+0=0; }
 *
 * If they are named, the name of the test statement is a concatenation of their names:
 *
 * @test(value="10+10=20" name="int addition" ) @test(value="10+0 = 10" name="zero neutrality")
 *
 * produces:
 *
 * test "int addition and zero neutrality" { assert 10+10=20; assert 10 + 0 = 10; }
 *
 * test annotations accept multi-line tests, provided that the last line is a boolean expression (i.e. an assertion).
 * Simply separate (as you would do in GAML) the lines by a semi-colon. If there are no assertion (i.e. the last line
 * ends with a semi-colon), the lines are simply copied to the GAML code. This can be handy if one wants to initialize a
 * bunch of variables, for instance. These statements can even contain complete 'assert' statements.
 *
 * Example:
 *
 * @test("int a <- 10; int b <- 10;") @test("a+b = 20") @test("a+0 = a") @test("int c<- 0; assert c+b = b;")
 *
 * produces:
 *
 * test "+" { int a <- 10; int b <- 10; assert a+b = 20; assert a+0 = a; int c<- 0; assert c+b = 0; }
 *
 * Note that no syntax verification occurs when writing these annotations. It is up to the programmer to produce
 * syntactically correct codes, otherwise the automated validation of models (which occurs whenever the code is
 * committed) will fail.
 *
 * @author drogoul
 *
 */
@Retention (RetentionPolicy.RUNTIME)
@Repeatable (tests.class)

public @interface test {
	/**
	 *
	 * @return the GAML expression or list of statements that need to be tested using the 'assert' statement. For
	 *         instance, '@test( "10+10 = 20")' will generate a test containing the statement 'assert 10+10 = 20;'
	 *
	 *         To generate a multi-line test, use semi-colons to separate the statements (like in GAML). For instance
	 *         '@test( "int a <- 10; int b <- 10; a+b = 20") will generate the following test:
	 *
	 *         test plus { int a <- 10; int b <- 10; assert a+b = 20; }
	 *
	 *         If the string ends with a semi-colon, no attempt is made to infer the 'assert' statement and the whole
	 *         GAML code is simply copied into the test. This can be used to initialize variables, but also to generate
	 *         tests that will "abort" instead of "failing". For instance, consider these two annotations:
	 *
	 *         '@test("int a <- 0; float b <- 100 / a ;")' // when tested, a runtime error will make this test abort
	 *         '@test("int a <- 0; !is_error(100 / a)")' // when tested, the runtime error will be caught but the test
	 *         will fail (as the division by zero IS an error)
	 *
	 *         An empty value will produce an empty test statement (unless the @test annotation is preceded or followed
	 *         by other @test annotations)
	 *
	 */
	String value();

	/**
	 *
	 * @return the name of the test (see the general comment for the effect of naming tests). It is empty by default.
	 */
	String name()

	default "";

	/**
	 *
	 * @return whether the test, if false, will fail or simply emit a warning. 'false' by default.
	 *
	 *         '@test("10+10 = 100" warning=true) will not be recorded as failing (i.e. it will not break the
	 *         compilation)
	 *
	 *         Note that warning=true has no effect if the value of the test does not contain assertions (and it simply
	 *         influences the last assertion if there is one)
	 */
	boolean warning() default false;

}